spring:
  application:
    name: store_eat
  datasource:
    url: jdbc:mysql://localhost:3306/osahaneat
    username: root
    password: 16082003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      #confif ma JWT
jwt:
  privateKey: yaXkMJZO9AVPm8qlZ1KG5kJG6OcnQGC1IQXVYtkkqYM=
  #config upload file
fileUpload:
  rootPath: C:/Users/admin/Desktop/uploads
  #config ghi log => tu dong lang nghe info -> debug -> warn
logging:
  level:
    root: info
#  file:
#    name: D:\BE\Intel\store_eat\ghi_log\dev.log


